from tkinter import *
root=Tk()
root.geometry("500x500")
menubar=Menu(root)
file=Menu(menubar,tearoff=0)
file.add_command(label="New ")
file.add_command(label="New Window")
file.add_command(label="Open")
file.add_command(label="Save")
file.add_command(label="Save As")
file.add_separator()
file.add_command(label="Pagesetup")
file.add_command(label="Print")
file.add_separator()
file.add_command(label="Exit")
menubar.add_cascade(label="File",menu=file)
edit=Menu(menubar,tearoff=0)
edit.add_command(label="Copy")
edit.add_command(label="Cut")
edit.add_command(label="paste")
edit.add_separator()
edit.add_command(label="undo")
edit.add_command(label="redo")
menubar.add_cascade(label="Edit",menu=edit)
forma=Menu(menubar,tearoff=0)
forma.add_command(label="Word Wrap")
forma.add_command(label="Font")
menubar.add_cascade(label="Format",menu=forma)
view=Menu(menubar,tearoff=0)
view.add_command(label="Zoom")
view.add_command(label="Status bar")
menubar.add_cascade(label="View",menu=view)
helps=Menu(menubar,tearoff=0)
helps.add_command(label="View help")
helps.add_command(label="Send Feedback")
helps.add_separator()
helps.add_command(label="About Notepad")
menubar.add_cascade(label="Help",menu=helps)
root.config(menu=menubar)
root.mainloop()
